(async()=>{
  const check=(v,m)=>{if(!v)throw Error(m)},sleep=ms=>new Promise(r=>setTimeout(r,ms));
  async function until(f,m){window.__markTestPhase=m;const end=performance.now()+4000;while(performance.now()<end){if(f())return;await sleep(30);}throw Error(m+' '+errors.join(';'));}
  window.requestAnimationFrame=fn=>setTimeout(()=>fn(performance.now()),16);window.cancelAnimationFrame=clearTimeout;
  document.documentElement.style.cssText='--color-surface-secondary:#303030;--color-text-secondary:#aaa;--color-text-tertiary:#888;--text-sm:14px;--text-xs:12px;--text-base:16px;--text-xl:28px;--font-weight-medium:500;--color-text:#ececec;--color-text-tertiary:#aaa;--color-border:#444;--color-surface:#202020;--color-surface-elevated-secondary:#282828;--height-token-row:40px;--padding-panel:24px;--padding-row-cell-x:12px;--thread-content-max-width:900px;color-scheme:dark';
  document.body.style.cssText='margin:0;background:#191919;color:#eee;font:14px system-ui';
  document.body.innerHTML='<div id="root"></div>';
  const tid='11111111-2222-3333-4444-555555555555',text='值得保存的内容',requests=[],errors=[];
  const records=[{id:'11111111-0000-4000-8000-111111111111',title:'收藏示例',quote:text,tags:[],thread_id:tid,thread_title:'来源任务',created_at:'2026-09-07T12:00:00Z',anchor:{message_id:'msg_test',turn_id:'turn1',coordinate_space:'rendered_message_text',text_sha256:await sha(text),dom_start_offset:0,dom_end_offset:text.length}}];
  window.codexMarks={library:async p=>{requests.push(p);const m=records[0];if(p.op==='search'){const rows=records.filter(r=>!!r.deleted_at===p.deleted&&(!p.query||r.quote.includes(p.query)));return {ok:true,marks:rows,total:rows.length};}if(p.op==='update'){m.title=p.title;m.tags=p.tags;m.note=p.note;}if(p.op==='delete')m.deleted_at='now';if(p.op==='restore')m.deleted_at=null;return {ok:true,mark:m,context:{status:'snapshot_verified',text,start_offset:0,end_offset:text.length}};}};
  const R=__native.React,j=__native.jsx,Context=R.createContext(null);
  const integration=createMarkSidebar({...__native,useNavigate:()=>R.useContext(Context).navigate,useLocation:()=>R.useContext(Context).location});
  const Rail=createMarksUI(R,j,{...__native,...__rail,Icon:()=>j.jsx('span',{children:'mark'})});
  const items=[{id:'turn1:user',turnKey:'turn1'}],getScrollElement=()=>document.querySelector('#scroll');
  function Navigation(){const item=integration.useItem();return j.jsx(__sidebarItem,{icon:item.icon,label:item.label,isActive:item.isCurrentDestination,onClick:item.onSelect,'data-test-mark-entry':''});}
  function App(){
    const [location,setLocation]=R.useState({pathname:'/',state:null});
    const navigate=(pathname,options)=>{requests.push({navigate:pathname});setLocation({pathname,state:options?.state});};
    return j.jsx(Context.Provider,{value:{location,navigate},children:j.jsxs('div',{style:{display:'flex',height:'600px',width:'800px'},children:[j.jsxs('aside',{style:{width:'180px',flexShrink:0,padding:'12px'},children:[j.jsx('p',{children:'新对话'}),j.jsx('p',{children:'插件'}),j.jsx(Navigation,{})]}),j.jsx('section',{'data-test-content':'',style:{flex:1,minWidth:0,minHeight:0,overflow:'hidden'},children:location.pathname==='/mark'?j.jsx(integration.Page,{}):location.pathname.startsWith('/local/')?j.jsxs('div',{style:{position:'relative',height:'100%'},children:[j.jsxs('div',{id:'scroll',style:{height:'560px',overflow:'auto'},children:[j.jsx('div',{style:{height:650}}),j.jsx('section',{'data-response-annotation-conversation':tid,'data-response-annotation-target':'msg_test',children:j.jsx('div',{'data-selected-text-overlay-target':'',children:text})}),j.jsx('div',{style:{height:700}})]}),j.jsx(Rail,{items,getScrollElement,navigate,pathname:location.pathname})]}):j.jsx('p',{children:'新对话'})})]})});
  }
  const root=__native.createRoot(document.querySelector('#root'),{onUncaughtError:e=>errors.push(e.message),onCaughtError:e=>errors.push(e.message)});root.render(j.jsx(__native.IntlProvider,{locale:'zh-CN',messages:{},onError:()=>{},children:j.jsx(App,{})}));
  const entry=()=>document.querySelector('[data-test-mark-entry]');
  await until(()=>entry(),'entry missing');entry().click();
  await until(()=>document.querySelector('.mark-library-row'),'native page failed');
  check(requests.some(r=>r.navigate==='/mark'),'sidebar did not navigate');
  check(entry().getAttribute('aria-current')==='page','route not selected');
  check(!document.querySelector('[role="dialog"]'),'library is still a dialog');
  const page=document.querySelector('[data-codex-mark-page]'),content=document.querySelector('[data-test-content]');
  check(page.getBoundingClientRect().left>=content.getBoundingClientRect().left,'page overlaps sidebar');
  check(page.getBoundingClientRect().right<=content.getBoundingClientRect().right+1,'page exceeds content region');
  check(document.querySelector('[role=tablist][aria-label="收藏范围"]'),'native tabs missing');
  check(document.querySelectorAll('[role=tab]').length===2,'contextless task tab should be absent');
  check(getComputedStyle(document.querySelector('[role=tab][aria-selected=true]')).backgroundColor!==getComputedStyle(document.querySelector('[role=tab][aria-selected=false]')).backgroundColor,'native selected background missing');
  check(page.querySelector('h1')?.textContent==='mark','native page title missing');
  check(page.querySelector('#mark-page-search'),'native page search missing');
  check(page.scrollWidth<=page.clientWidth+1,'page horizontal overflow');
  const input=page.querySelector('#mark-page-search');
  const setValue=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set;
  setValue.call(input,'没有匹配');input.dispatchEvent(new Event('input',{bubbles:true}));
  await until(()=>Array.from(document.querySelectorAll('p')).some(p=>p.textContent.includes('没有找到匹配')),'native search did not filter');
  setValue.call(input,'');input.dispatchEvent(new Event('input',{bubbles:true}));
  await until(()=>document.querySelector('.mark-library-row'),'clearing search failed');
  document.querySelector('.mark-library-row').click();await until(()=>document.querySelector('.mark-text-preview mark'),'highlight missing');
  const findButton=t=>Array.from(document.querySelectorAll('button')).find(b=>b.textContent===t);
  check(!findButton('上一页')&&!findButton('下一页'),'unneeded pagination shown');
  check(document.querySelector('.mark-detail-actions').getBoundingClientRect().top<document.querySelector('.mark-preview').getBoundingClientRect().top,'source actions below preview');
  check(summaryOf({quote:'flowchart LR A-->B',anchor:{block_kind:'mermaid'}}).includes('查看完整图表'),'raw Mermaid summary');
  check(summaryOf({quote:'| 名称 | 说明 |\n| --- | --- |',anchor:{block_kind:'table'}})==='表格 · 名称 / 说明','table header summary');
  findButton('查看上下文').click();await until(()=>findButton('只看收藏片段'),'context toggle failed');findButton('只看收藏片段').click();
  document.querySelector('.mark-edit summary').click();check(findButton('保存修改').disabled,'unchanged save enabled');
  const tagsInput=document.querySelector('[aria-label="标签"]');setValue.call(tagsInput,'学习，项目');tagsInput.dispatchEvent(new Event('input',{bubbles:true}));
  await until(()=>document.querySelector('.mark-unsaved'),'dirty state missing');
  findButton('保存修改').click();await until(()=>records[0].tags.length===2&&!document.querySelector('.mark-unsaved'),'tags not normalized after save');
  check(findButton('保存修改').disabled,'saved form remains dirty');
  Array.from(document.querySelectorAll('button')).find(b=>b.textContent==='移到回收站').click();await until(()=>records[0].deleted_at,'delete failed');
  Array.from(document.querySelectorAll('button')).find(b=>b.textContent==='回收站').click();await until(()=>document.querySelector('.mark-library-row'),'trash missing');
  document.querySelector('.mark-library-row').click();await until(()=>Array.from(document.querySelectorAll('button')).some(b=>b.textContent==='恢复收藏'),'restore unavailable');
  Array.from(document.querySelectorAll('button')).find(b=>b.textContent==='恢复收藏').click();await until(()=>!records[0].deleted_at,'restore failed');
  Array.from(document.querySelectorAll('button')).find(b=>b.textContent==='全部').click();await until(()=>document.querySelector('.mark-library-row'),'all missing');
  document.querySelector('.mark-library-row').click();await until(()=>document.querySelector('.mark-text-preview'),'detail missing');
  Array.from(document.querySelectorAll('button')).find(b=>b.textContent==='定位原文').click();
  await until(()=>document.querySelector('[data-codex-mark-nav-id]'),'task not mounted');
  await until(()=>getScrollElement().scrollTop>100,'source position lost');
  check(!entry().hasAttribute('aria-current'),'mark remains selected on source task');
  entry().click();await until(()=>document.querySelector('.mark-library-row'),'sidebar entry did not open page');
  check(!document.querySelector('[role="dialog"]'),'sidebar entry still creates a dialog');
  const tabs=Array.from(document.querySelectorAll('[role=tab]'));
  check(tabs.length===3,'source task tab missing');
  const first=tabs[0];first.focus();first.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true}));
  await until(()=>tabs[1].getAttribute('aria-selected')==='true','native ArrowRight failed');
  check(document.activeElement===tabs[1],'native focus did not follow tab');
  check(tabs[0].tabIndex===-1&&tabs[1].tabIndex===0,'native roving tabindex incorrect');
  tabs[1].dispatchEvent(new KeyboardEvent('keydown',{key:'End',bubbles:true}));
  await until(()=>tabs[2].getAttribute('aria-selected')==='true','native End failed');
  tabs[2].dispatchEvent(new KeyboardEvent('keydown',{key:'Home',bubbles:true}));
  await until(()=>tabs[0].getAttribute('aria-selected')==='true','native Home failed');
  check(document.getElementById(tabs[0].getAttribute('aria-controls'))?.getAttribute('role')==='tabpanel','tab panel not associated');
  await until(()=>document.querySelector('.mark-library-row'),'tab restore failed');
  check(!Array.from(document.querySelectorAll('button')).find(b=>b.textContent==='当前任务').disabled,'source task context lost');
  document.querySelector('.mark-library-row').click();await until(()=>document.querySelector('.mark-text-preview mark'),'final detail missing');
  check(document.querySelector('.mark-detail').getBoundingClientRect().right<=document.querySelector('[data-test-content]').getBoundingClientRect().right+1,'detail extends outside page');
  check(!errors.length,errors.join(';'));
  return JSON.stringify({ok:true,checks:37,actualHostComponents:['SidebarItem','PageLayout','Search','Button','Input','Tabs'],requestCount:requests.length});
})()
